# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 22 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'review' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: newest-metrics.svg
          output_action: pull-request
          committer_branch: ${{ github.head_ref || github.ref_name }}  # Gets only the branch name from refs/heads/branch_name
          committer_message: "chore: CRON metrics rendering task"
          # Options
          template: classic
          base: repositories, metadata
          base_indepth: yes
          commits_authoring: pierre-manchon
          config_display: columns
          config_timezone: Europe/Paris
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 25
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: top
          plugin_music_provider: spotify
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_user: lVUD34RjQzqWY-lzWDTscg
          plugin_traffic: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          output_action: pull-request-merge
